// lib/tokens.js
// Master token list — tags are placeholders pending full classification
// Tag values: agent-independent | agent-via-virtuals | agent-via-clanker | agent-via-bankr |
//             clanker-via-bankrbot-prefork | non-agent-via-bankr | non-agent-via-clanker |
//             non-agent-via-virtuals | non-agent-infrastructure | neither

const tokens = [

  // ── AGENT INDEPENDENT ─────────────────────────────────────────────────────
  { name: "Virtuals Protocol",             symbol: "VIRTUAL",  address: "0x0b3e328455c4059EEb9e3f84b5543F74E24e7E1b", tag: "agent-independent" },
  { name: "Clanker",                       symbol: "CLANKER",  address: "0x1bc0c42215582d5a085795f4badbac3ff36d1bcb", tag: "agent-independent" },
  { name: "Venice",                        symbol: "VENICE",   address: "0xacfE6019Ed1A7Dc6f7B508C02d1b04ec88cC21bf", tag: "agent-independent" },
  { name: "AWE",                           symbol: "AWE",      address: "0x1b4617734c43f6159f3a70b7e06d883647512778", tag: "agent-independent" },
  { name: "FAI (Freysa)",                  symbol: "FAI",      address: "0xb33Ff54b9F7242EF1593d2C9Bcd8f9df46c77935", tag: "agent-independent" },
  { name: "Bankr",                         symbol: "BNKR",     address: "0x22af33fe49fd1fa80c7149773dde5890d3c76f3b", tag: "agent-independent" },
  { name: "AI Agent Layer",               symbol: "AIFUN",    address: "0xbdf317f9c153246c429f23f4093087164b145390", tag: "agent-independent" },
  { name: "AI Rig Complex",               symbol: "ARC",      address: "0x61ca70b867a48265e553a7fbb81bfe44fada7ae6", tag: "agent-independent" },
  { name: "Agent Zero",                    symbol: "A0T",      address: "0xcc4adb618253ed0d4d8a188fb901d70c54735e03", tag: "agent-independent" },
  { name: "ElizaOS",                       symbol: "ELIZAOS",  address: "0xea17df5cf6d172224892b5477a16acb111182478", tag: "agent-independent" },
  { name: "Autonolas",                     symbol: "OLAS",     address: "0x54330d28ca3357f294334bdc454a032e7f353416", tag: "agent-independent" },
  { name: "Cookie DAO",                    symbol: "COOKIE",   address: "0xc0041ef357b183448b235a8ea73ce4e4ec8c265f", tag: "agent-independent" },
  { name: "AITECH Cloud Network",          symbol: "ACN",      address: "0xd71552d9e08e5351adb52163b3bbbc4d7de53ce1", tag: "agent-independent" },
  { name: "Morpheus AI",                   symbol: "MOR",      address: "0x7431ada8a591c955a994a21710752ef9b882b8e3", tag: "agent-independent" },
  { name: "Artificial Liquid Intelligence",symbol: "ALI",      address: "0x97c806e7665d3afd84a8fe1837921403d59f3dcc", tag: "agent-independent" },
  { name: "Cortex",                        symbol: "CTXC",     address: "0x000000000000012def132e61759048be5b5c6033", tag: "agent-independent" },
  { name: "Wayfinder",                     symbol: "PROMPT",   address: "0x30c7235866872213f68cb1f08c37cb9eccb93452", tag: "agent-independent" },
  { name: "GAME by Virtuals",              symbol: "GAME",     address: "0x1c4cca7c5db003824208adda61bd749e55f463a3", tag: "agent-independent" },
  { name: "Elsa",                          symbol: "ELSA",     address: "0x29cc30f9d113b356ce408667aa6433589cecbdca", tag: "agent-independent" },
  { name: "Faircaster",                    symbol: "FAIR",     address: "0x4e6c9f48f73e54ee5f3ab7e2992b2d733d0d0b07", tag: "agent-independent" }, // Clanker-deployed but confirmed autonomous agent
  { name: "SMC Factory",                   symbol: "SMCF",     address: null,                                          tag: "agent-independent" }, // address TBD
  { name: "Spectral",                      symbol: "SPEC",     address: "0x96419929d7949d6a801a6909c145c8eef6a40431", tag: "agent-independent" },

  // ── AGENT VIA VIRTUALS ────────────────────────────────────────────────────
  { name: "AIXBT",                         symbol: "AIXBT",    address: "0x4f9fd6be4a90f2620860d680c0d4d5fb53d1a825", tag: "agent-via-virtuals" },
  { name: "Ethy AI",                       symbol: "ETHY",     address: "0xC44141a684f6AA4E36cD9264ab55550B03C88643", tag: "agent-via-virtuals" },
  { name: "Axelrod",                       symbol: "AXLROD",   address: "0x58Db197E91Bc8Cf1587F75850683e4bd0730e6BF", tag: "agent-via-virtuals" },
  { name: "VADER",                         symbol: "VADER",    address: "0x731814e491571a2e9ee3c5b1f7f3b962ee8f4870", tag: "agent-via-virtuals" },
  { name: "Ribbita",                       symbol: "RIBBITA",  address: "0xA4A2E2ca3fBfE21aed83471D28b6f65A233C6e00", tag: "agent-via-virtuals" },
  { name: "LUNA (Virtuals)",               symbol: "LUNA",     address: "0x55cd6469f597452b5a7536e2cd98fde4c1247ee4", tag: "agent-via-virtuals" },
  { name: "BYTE",                          symbol: "BYTE",     address: null,                                          tag: "agent-via-virtuals" }, // address under review
  { name: "SWARM",                         symbol: "SWARM",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "ATHENA",                        symbol: "ATHENA",   address: null,                                          tag: "agent-via-virtuals" },
  { name: "PRXVT",                         symbol: "PRXVT",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "Litebeam",                      symbol: "LBEAM",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "ReplyCorp",                     symbol: "REPLY",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "Instaclaw",                     symbol: "INSTA",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "Chromia EVAL",                  symbol: "CEVAL",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "BLACK HOLE",                    symbol: "BHOLE",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "Music by Virtuals",             symbol: "MUSIC",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "Iona",                          symbol: "IONA",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "Aurra",                         symbol: "AURRA",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "GAM3S.GG",                      symbol: "G3",       address: null,                                          tag: "agent-via-virtuals" },
  { name: "DTRXBT",                        symbol: "DTRXBT",   address: null,                                          tag: "agent-via-virtuals" },
  { name: "CONVO",                         symbol: "CONVO",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "Sage",                          symbol: "SAGE",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "A.T.M.",                        symbol: "ATM",      address: null,                                          tag: "agent-via-virtuals" },
  { name: "Wakehacker",                    symbol: "WAKE",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "VERONICA",                      symbol: "VRON",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "Waveform",                      symbol: "WAVE",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "MUTE SWAP",                     symbol: "MUTE",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "Velvet Unicorn",                symbol: "VU",       address: null,                                          tag: "agent-via-virtuals" },
  { name: "Rabbi Schlomo",                 symbol: "RABBI",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "Cybercentry",                   symbol: "CYBER",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "Predi",                         symbol: "PREDI",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "Replicat-One",                  symbol: "R1",       address: null,                                          tag: "agent-via-virtuals" },
  { name: "Starly",                        symbol: "STARLY",   address: null,                                          tag: "agent-via-virtuals" },
  { name: "Upsider AI",                    symbol: "UPAI",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "Jeff CEO",                      symbol: "JEFF",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "LYRA",                          symbol: "LYRA",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "717ai",                         symbol: "717",      address: null,                                          tag: "agent-via-virtuals" },
  { name: "1000x",                         symbol: "1000X",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "SIBYL",                         symbol: "SIBYL",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "Acolyte",                       symbol: "ACOL",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "Loky",                          symbol: "LOKY",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "Gekko AI",                      symbol: "GEKKO",    address: "0xf7b0dd0B642a6ccc2fc4d8FfE2BfFb0caC8C43C8", tag: "agent-via-virtuals" },
  { name: "Degenerate SQuiD",             symbol: "SQDGN",    address: "0x4674F73545F1db4036250ff8C33A39ad1678D864", tag: "agent-via-virtuals" },
  { name: "Robostack",                     symbol: "ROBOT",    address: "0x708c2B2eEb9578dFe4020895139E88F7654647Ff", tag: "agent-via-virtuals" },
  { name: "maicrotrader",                  symbol: "MAICRO",   address: "0xE74731ba9d1Da6Fd3C8c60Ff363732bebAc5273E", tag: "agent-via-virtuals" },
  { name: "Fyni AI",                       symbol: "FYNI",     address: "0x22c0a2e55AeD8B317A285ccbd4f3D8eE24C9e5e3", tag: "agent-via-virtuals" },
  { name: "Solace",                        symbol: "SOLACE",   address: null,                                          tag: "agent-via-virtuals" },
  { name: "Neurobro",                      symbol: "NBRO",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "Capminal",                      symbol: "CAP",      address: null,                                          tag: "agent-via-virtuals" },
  { name: "Otto AI",                       symbol: "OTTO",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "Osobot",                        symbol: "OSO",      address: null,                                          tag: "agent-via-virtuals" },
  { name: "SANTA",                         symbol: "SANTA",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "VPay",                          symbol: "VPAY",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "AUTONOMOPOLY",                  symbol: "AUTO",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "ArAIstotle",                    symbol: "ARAIS",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "SIRE",                          symbol: "SIRE",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "Aubrai",                        symbol: "AUBRAI",   address: null,                                          tag: "agent-via-virtuals" },
  { name: "Jaihoz",                        symbol: "JAIHOZ",   address: null,                                          tag: "agent-via-virtuals" },
  { name: "Maya World",                    symbol: "MAYA",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "Degen AI",                      symbol: "DGNAI",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "nomAI",                         symbol: "NOMAI",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "Kolwaii",                       symbol: "KOL",      address: null,                                          tag: "agent-via-virtuals" },
  { name: "WachAI",                        symbol: "WACH",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "0xMonk",                        symbol: "MONK",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "Gigabrain",                     symbol: "GBRAIN",   address: null,                                          tag: "agent-via-virtuals" },
  { name: "Olyn",                          symbol: "OLYN",     address: null,                                          tag: "agent-via-virtuals" },
  { name: "Gloria AI",                     symbol: "GLORIA",   address: null,                                          tag: "agent-via-virtuals" },
  { name: "ARGUE.FUN",                     symbol: "ARGUE",    address: null,                                          tag: "agent-via-virtuals" },
  { name: "SIMMI",                         symbol: "SIMMI",    address: null,                                          tag: "agent-via-virtuals" },

  // ── AGENT VIA CLANKER ─────────────────────────────────────────────────────
  { name: "CLAWD",                         symbol: "CLAWD",    address: "0x9f86db9fc6f7c9408e8fda3ff8ce4e78ac7a6b07", tag: "clanker-via-bankrbot-prefork" },
  { name: "Clawnch",                       symbol: "CLAWNCH",  address: "0xa1f72459dfa10bad200ac160ecd78c6b77a747be", tag: "clanker-via-bankrbot-prefork" },
  { name: "KellyClaude",                   symbol: "KCLAUDE",  address: "0x50d2280441372486beecdd328c1854743ebacb07", tag: "clanker-via-bankrbot-prefork" },
  { name: "FELIX",                         symbol: "FELIX",    address: "0xf30bf00edd0c22db54c9274b90d2a4c21fc09b07", tag: "clanker-via-bankrbot-prefork" },
  { name: "Juno Agent",                    symbol: "JUNO",     address: "0x4e6c9f48f73e54ee5f3ab7e2992b2d733d0d0b07", tag: "clanker-via-bankrbot-prefork" },
  { name: "ClawBank",                      symbol: "CLAWBANK", address: "0x16332535E2c27da578bC2e82bEb09Ce9d3C8EB07", tag: "agent-via-clanker" },
  { name: "Sairi",                         symbol: "SAIRI",    address: "0xde61878b0b21ce395266c44d4d548d1c72a3eb07", tag: "agent-via-clanker" }, // low confidence, included pending review

  // ── AGENT VIA BANKR ───────────────────────────────────────────────────────
  { name: "Gitlawb",                       symbol: "GITLAWB",  address: "0x5f980dcfc4c0fa3911554cf5ab288ed0eb13dba3", tag: "agent-via-bankr" },

  // ── NON-AGENT VIA BANKR ───────────────────────────────────────────────────
  { name: "Surplus Intelligence",          symbol: "SURP",     address: "0xc52aedec3374422d7510e294cfaa90799595cba3", tag: "non-agent-via-bankr" },
  { name: "aeon",                          symbol: "AEON",     address: "0xBf8E8f0e8866a7052F948C16508644347c57aba3", tag: "non-agent-via-bankr" },
  { name: "nookplot",                      symbol: "NOOK",     address: "0xb233bdffd437e60fa451f62c6c09d3804d285ba3", tag: "non-agent-via-bankr" },
  { name: "BOTCOIN",                       symbol: "BOTCOIN",  address: "0xa601877977340862ca67f816eb079958e5bd0ba3", tag: "non-agent-via-bankr" },
  { name: "Root Edge",                     symbol: "ROOT",     address: "0x461d3c96d170e551611f54fa466d3d74a680aba3", tag: "non-agent-via-bankr" },
  { name: "Robot Money",                   symbol: "ROBOT",    address: "0x65021a79aeef22b17cdc1b768f5e79a8618beba3", tag: "non-agent-via-bankr" },
  { name: "Basemate",                      symbol: "BASE",     address: "0x07E61D8a4e197dfC269e90D7ECe1dF0D26702bA3", tag: "non-agent-via-bankr" },
  { name: "Ratspeak",                      symbol: "RATS",     address: "0xf1e9baa65d418a9025e1851dd2d37f1ad208bba3", tag: "non-agent-via-bankr" },
  { name: "FreeCode",                      symbol: "FREE",     address: "0x67a7ca081dc79b45fd1fa059cd3b8dcca779aba3", tag: "non-agent-via-bankr" },
  { name: "Blocktronics",                  symbol: "BLOCK",    address: "0x7afe438411ee3959c7de6f7fb76bf9c769320ba3", tag: "non-agent-via-bankr" },
  { name: "cyb3rwr3n",                     symbol: "CYB3R",    address: "0x26E6e2E7a9289B6485c53Cd498dE510d3a8c8ba3", tag: "non-agent-via-bankr" },
  { name: "DARKSOL",                       symbol: "DARKSOL",  address: "0x00cb1fbca324d51325a7264d54072bc073c28ba3", tag: "non-agent-via-bankr" },
  { name: "Delu",                          symbol: "DELU",     address: "0x7b0ee9dcb5c1d4d7cd630c652959951936512ba3", tag: "non-agent-via-bankr" },
  { name: "grantr",                        symbol: "GRANTR",   address: "0x753f2af0f46361c9ae6fc347797f99b0c9e82ba3", tag: "non-agent-via-bankr" },
  { name: "LITCOIN",                       symbol: "LIT",      address: "0x316ffb9c875f900adcf04889e415cc86b564eba3", tag: "non-agent-via-bankr" },
  { name: "WOON",                          symbol: "WOON",     address: "0x85eac631c800af804476b140f87039f742c28ba3", tag: "non-agent-via-bankr" },
  { name: "1clawAI",                       symbol: "1CLAW",    address: "0x61d91cff0fc9fbbdb89f505cf8a7422bf95fdba3", tag: "non-agent-via-bankr" },
  { name: "evo",                           symbol: "EVO",      address: "0x721b072dbb616f29eea73ac004e03fd4e884bba3", tag: "non-agent-via-bankr" },
  { name: "HermesOS",                      symbol: "HERMES",   address: "0x95ccfD2B81A9667b0Cc979992632F98fc853EBa3", tag: "non-agent-via-bankr" },
  { name: "MiroShark",                     symbol: "MIRO",     address: "0xd7bc6a05a56655FB2052F742B012d1DFD66e1BA3", tag: "non-agent-via-bankr" },
  { name: "TACHI",                         symbol: "TACHI",    address: "0x39b4b879b8521d6a8c3a87cda64b969327b7fba3", tag: "non-agent-via-bankr" },
  { name: "HALO",                          symbol: "HALO",     address: "0x0a56431ecc9d0b39be0b1e27e795f4c4f19d0ba3", tag: "non-agent-via-bankr" },
  { name: "LienFi",                        symbol: "LIEN",     address: "0x3722264aB15a1dfCe5a5af89e6547F7949A8ABA3", tag: "non-agent-via-bankr" },
  { name: "Atlas",                         symbol: "ATLAS",    address: null,                                          tag: "non-agent-via-bankr" },
  { name: "Polygraph",                     symbol: "POLY",     address: null,                                          tag: "non-agent-via-bankr" },
  { name: "TEMPO",                         symbol: "TEMPO",    address: null,                                          tag: "non-agent-via-bankr" },
  { name: "A2H",                           symbol: "A2H",      address: null,                                          tag: "non-agent-via-bankr" },
  { name: "Protean",                       symbol: "PRTN",     address: null,                                          tag: "non-agent-via-bankr" },

  // ── NON-AGENT VIA CLANKER ─────────────────────────────────────────────────
  { name: "Moltbook",                      symbol: "MOLT",     address: "0xB695559b26BB2c9703ef1935c37AeaE9526bab07", tag: "non-agent-via-clanker" },
  { name: "DebtReliefBot",                 symbol: "DRB",      address: null,                                          tag: "non-agent-via-clanker" },
  { name: "Defense of the Agents",         symbol: "DOTA",     address: null,                                          tag: "non-agent-via-clanker" },
  { name: "ProductClank",                  symbol: "PCLNK",    address: null,                                          tag: "non-agent-via-clanker" },
  { name: "Cody",                          symbol: "CODY",     address: null,                                          tag: "non-agent-via-clanker" },
  { name: "luminous",                      symbol: "LUM",      address: null,                                          tag: "non-agent-via-clanker" },
  { name: "Regent",                        symbol: "REGENT",   address: null,                                          tag: "non-agent-via-clanker" },
  { name: "RETAKE.TV",                     symbol: "RETAKE",   address: null,                                          tag: "non-agent-via-clanker" },
  { name: "BETRMINT",                      symbol: "BETR",     address: null,                                          tag: "non-agent-via-clanker" },
  { name: "airgap.finance",                symbol: "AIRGAP",   address: null,                                          tag: "non-agent-via-clanker" },
  { name: "A0x",                           symbol: "A0X",      address: null,                                          tag: "non-agent-via-clanker" },
  { name: "Zoe",                           symbol: "ZOE",      address: null,                                          tag: "non-agent-via-clanker" },

  // ── NON-AGENT VIA VIRTUALS ────────────────────────────────────────────────
  { name: "Shadow Combat League",          symbol: "SCL",      address: null,                                          tag: "non-agent-via-virtuals" },
  { name: "PEAK",                          symbol: "PEAK",     address: null,                                          tag: "non-agent-via-virtuals" },
  { name: "VIRGEN",                        symbol: "VIRGEN",   address: null,                                          tag: "non-agent-via-virtuals" },
  { name: "Bio Unit 000",                  symbol: "BIO",      address: null,                                          tag: "non-agent-via-virtuals" },
  { name: "Agent YP",                      symbol: "YP",       address: null,                                          tag: "non-agent-via-virtuals" },
  { name: "DessalinesAI",                  symbol: "DESS",     address: null,                                          tag: "non-agent-via-virtuals" },
  { name: "Gluteus Maximus",               symbol: "GLUTE",    address: null,                                          tag: "non-agent-via-virtuals" },
  { name: "Fabric Protocol",               symbol: "ROBO",     address: null,                                          tag: "non-agent-via-virtuals" },

  // ── NON-AGENT INFRASTRUCTURE ──────────────────────────────────────────────
  { name: "Hive Intelligence",             symbol: "HINT",     address: "0x91dA780BC7f4B7Cf19ABE90411a2a296Ec5FF787", tag: "non-agent-infrastructure" },
  { name: "Rivalz Token",                  symbol: "RIZ",      address: "0x67543CF0304C19CA62AC95ba82FD4F4B40788dc1", tag: "non-agent-infrastructure" },
  { name: "Mythos Router",                 symbol: "MYTHOS",   address: "0xb942B75A602fA318ac091370D93d9143Ba345Ba3", tag: "non-agent-infrastructure" },

  // ── NEEDS REVISIT ─────────────────────────────────────────────────────────
  { name: "SWARM",                         symbol: "SWARM",    address: null,                                          tag: "neither" }, // in revisit bucket
  { name: "AXOBOTL",                       symbol: "AXOBOTL",  address: "0xe081a28a3f5a044d2d7681605330368142c17264", tag: "neither" },
  { name: "Wasabot",                       symbol: "WASA",     address: "0xdE7C47527D3778e5dB7EB2abB97C19511e44c1CE", tag: "neither" },

];

export default tokens;
